# Generated by Django 2.1.2 on 2018-10-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_remove_tweet_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete='', to='tweets.Tweet'),
        ),
    ]
